---
title: "Adj DK Pts with Course Fit Sim"
author: "Jarrod Pelkofer"
date: "3/31/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r}
library(plotly)
library(DataExplorer)

source(file = "simulation_scripts/adj_dk_course_fit_sim_script.R")

plan(multisession, workers = 4)

theme_set(theme_minimal())

```

# Read in Past Hole Category Data
```{r}
hole_category_values <- 
  read_csv("cluster_holes/past_holes_categorized/hole_categories_tbl.csv") %>% 
  group_by(hole_category) %>% 
  summarise(min_adj_field_dk_avg = min(adj_field_dk_avg, na.rm = TRUE),
            max_adj_field_dk_avg = max(adj_field_dk_avg, na.rm = TRUE)) %>% 
  filter(hole_category == "medium") %>% 
  pivot_longer(-hole_category) %>% 
  pull(value)
```

# Pull tournament to sim
```{r}
tournament_players_tbl <- 
  read_rds("tournament_players_tbl.rds")
```

# Run Simulations - non weighted recent form
```{r}
adj_dk_course_fit_sims_summarized <- 
  tournament_players_tbl %>%
  select(data) %>% 
  pmap(purrr::possibly(~ complete_simulation_framework(.x, cut_range = 70, six_week_weight = 1,
                                                      three_month_weight = 1, six_month_weight = 1), otherwise = NA))

adj_dk_course_fit_sims_tbl <- 
  adj_dk_course_fit_sims_summarized %>% 
  enframe(value = "sims") %>% 
  unnest(sims)

adj_dk_course_fit_sims_tbl %>%
  select(-name) %>% 
  mutate(sim_type = "adjusted_with_course_fit") %>% 
  write_csv("simulation_results/adjusted_with_course_fit_sims.csv")
```

# All 2019 season sims with six-week and three-month weighted scores
```{r}
adj_dk_course_fit_sims_summarized <- 
  tournament_players_tbl %>%
  select(data) %>% 
  pmap(purrr::possibly(~ complete_simulation_framework(.x, cut_range = 70, six_week_weight = 1.60,
                                                      three_month_weight = 1.30, six_month_weight = 1), otherwise = NA))

adj_dk_course_fit_sims_tbl <- 
  adj_dk_course_fit_sims_summarized %>% 
  enframe(value = "sims") %>% 
  unnest(sims)

adj_dk_course_fit_sims_tbl %>%
  select(-name) %>% 
  mutate(sim_type = "adjusted_course_fit_weighted_recent_form") %>% 
  write_csv("simulation_results/adjusted_course_fit_weighted_recent_form.csv")
```
