---
title: "adjusting_hole_scores"
author: "Jarrod Pelkofer"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries, Connect to DB, Set Cores, Load Feature Functions
```{r}
library(DBI)
library(RPostgres)
library(tidyverse)
library(lubridate)
library(tidymodels)
library(timetk)
library(DataExplorer)
library(embed)
library(furrr)
library(plotly)

plan(multisession, workers = 4)

con <- dbConnect(drv = RPostgres::Postgres(), 
                 user = "postgres", 
                 password = keyring::key_get("postgres_db", "postgres"), 
                 dbname = "golf_db",
                 )

source(file = "feature_scripts/create_features.R")

theme_set(theme_minimal())
```

```{r}
# pull in holes data
holes_tbl <- 
  tbl(con, "holes_tbl") %>%
  filter(date %>% between(left = lubridate::ymd("2015-10-16"), right = lubridate::ymd("2019-01-09"))) %>% 
  arrange(date, round, hole) %>% 
  mutate(player_name = case_when(
    player_name == "Ali Al-Shahrani" ~ "Ali Al Shahrani",
    TRUE ~ player_name
  )) %>%
  collect()

# pull in rounds data
rounds_tbl <- 
  tbl(con, "rounds_tbl") %>%
  filter(date %>% between(left = lubridate::ymd("2015-10-16"), right = lubridate::ymd("2019-01-09"))) %>%
  arrange(date, round) %>%
  mutate(player_name = case_when(
    player_name == "Ali Al-Shahrani" ~ "Ali Al Shahrani",
    TRUE ~ player_name
  )) %>%
  collect()


```

# Features
```{r}

overall_round_data <- overall_round_features(holes_tbl)

overall_holes_data <- overall_hole_features(holes_tbl)

player_round_data <- player_smoothing_features(holes_tbl)

    
```

# Use Recipes to Create Dummy Variables for each course/rd combo and all players
```{r}

rounds_rec <- 
  recipe( ~ ., data = player_round_data) %>% 
  step_dummy(all_nominal(), one_hot = TRUE)

rounds_data_baked <- 
  rounds_rec %>% prep() %>% bake(new_data = NULL)

```

# Modeling Round Difficulty
```{r}
birdie_rate_lm <- 
  rounds_data_baked %>%
  select(
    birdie_or_better_rate,
    birdie_or_better_rate_smoothed,
    contains("player_name"),
    contains("course_rd_id")
  ) %>%
  lm(birdie_or_better_rate ~ ., data = .)

adj_birdie_rates <- 
  tidy(birdie_rate_lm) %>% 
  filter(term %>% str_detect("course_rd_id")) %>% 
  arrange(desc(estimate)) %>% 
  mutate(term = term %>% str_sub(15, -1)) %>% 
  select(term, birdie_rate_adj = estimate)

bogey_rate_lm <- 
  rounds_data_baked %>%
  select(
    bogeys_or_worse_rate,
    bogeys_or_worse_rate_smoothed,
    contains("player_name"),
    contains("course_rd_id")
  ) %>%
  lm(bogeys_or_worse_rate ~ ., data = .)

adj_bogey_rates <- 
  tidy(bogey_rate_lm) %>% 
  filter(term %>% str_detect("course_rd_id")) %>% 
  arrange(desc(estimate)) %>% 
  mutate(term = term %>% str_sub(15, -1)) %>% 
  select(term, bogey_rate_adj = estimate)

dk_pts_rd_lm <- 
  rounds_data_baked %>%
  select(
    dk_hole_pts_in_rd,
    dk_hole_pts_in_rd_smoothed,
    contains("player_name"),
    contains("course_rd_id")
  ) %>%
  lm(dk_hole_pts_in_rd ~ ., data = .)

adj_dk_pts_lm <- 
  tidy(dk_pts_rd_lm) %>% 
  filter(term %>% str_detect("course_rd_id")) %>% 
  arrange(desc(estimate)) %>% 
  mutate(term = term %>% str_sub(15, -1)) %>% 
  select(term, dk_pts_adj = estimate)

```

# Kmeans Feature Set
```{r}
kmeans_feature_set <- 
  overall_holes_data %>% 
  left_join(adj_birdie_rates, by = c("course_rd_id" = "term")) %>% 
  left_join(adj_bogey_rates, by = c("course_rd_id" = "term")) %>%
  left_join(adj_dk_pts_lm, by = c("course_rd_id" = "term")) %>% 
  mutate(adj_birdie_or_better_rate = birdie_or_better_rate + birdie_rate_adj,
         adj_bogey_or_worse_rate = bogeys_or_worse_rate + bogey_rate_adj,
         adj_dk_pts_avg = field_dk_classic_avg + (dk_pts_adj/18)) %>% 
  select(course_rd_hole_id, par, yards, adj_birdie_or_better_rate:adj_dk_pts_avg)

kmeans_feature_set %>% plot_missing()
```


# Kmeans Clustering of Holes
```{r}


# kmeans recipe
cluster_rec <- 
  recipe(course_rd_hole_id ~ ., data = kmeans_feature_set) %>% 
  step_knnimpute(yards, adj_birdie_or_better_rate, adj_bogey_or_worse_rate, adj_dk_pts_avg) %>% 
  step_normalize(all_predictors())

# prepare data for kmeans
holes_kmeans_baked_data <- cluster_rec %>% prep() %>% bake(new_data = NULL)

holes_kmeans_baked_data %>% plot_missing()

# kmeans function
kmeans_mapper <- function(centers = 3) {
    
    holes_kmeans_baked_data %>%
        select(-course_rd_hole_id) %>%
        kmeans(centers = centers, nstart = 1)
  
}

kmeans_mapped_tbl <- 
    tibble(centers = 1:9) %>%
    mutate(k_means = centers %>% map(kmeans_mapper)) %>%
    mutate(glance  = k_means %>% map(glance))

kmeans_mapped_tbl %>% 
  unnest(glance) %>% 
  select(centers, tot.withinss) %>% 
  ggplot(aes(centers, tot.withinss)) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = c(1:9))

#pluck centers = 5
kmeans_4_obj <- 
  kmeans_mapped_tbl %>% 
  pull(k_means) %>% 
  purrr::pluck(4)

kmeans_joined_data <- 
  kmeans_4_obj %>% 
  augment(holes_kmeans_baked_data)
```

# Umap
```{r}
umap_rec <- 
  recipe(~ . , data = kmeans_feature_set) %>% 
  update_role(course_rd_hole_id, new_role = "id") %>% 
  step_knnimpute(yards, adj_birdie_or_better_rate, adj_bogey_or_worse_rate, adj_dk_pts_avg) %>% 
  step_normalize(all_predictors()) %>% 
  step_umap(all_predictors())

holes_umap_data <- umap_rec %>% prep() %>% bake(new_data = NULL)

umap_g1 <- 
  holes_umap_data %>% 
  left_join(kmeans_feature_set) %>%
  left_join(select(kmeans_joined_data, course_rd_hole_id, .cluster)) %>% 
  mutate(label = str_glue("Par: {par}
                          Yards: {yards}
                          DK_Round_Pts_Adj: {adj_dk_pts_avg}
                          cluster: {.cluster}")) %>% 
  ggplot(aes(umap_1, umap_2)) + 
  geom_point(aes(color = .cluster, text = label), alpha = .7)

ggplotly(umap_g1)
```


```{r}
holes_tbl %>% 
  unite("course_rd_hole_id", c(season:course_id, round, hole)) %>%
  left_join(select(kmeans_joined_data, course_rd_hole_id, .cluster)) %>%
  filter(.cluster == 1) %>%
  group_by(player_name) %>% 
  summarise(total_holes = n(),
            avg_dk_pts_gained = mean(dk_pts_gained_classic)) %>% 
  ungroup() %>% 
  arrange(desc(avg_dk_pts_gained)) %>% 
  filter(total_holes > 300)



```


```{r}
  
hole_samples_nested_tbl <- 
  holes_clustered_tbl %>% 
  group_by(.cluster, score_type) %>% 
  summarise(total = round(n()/100, 0)) %>% 
  mutate(modified_total = if_else(score_type == "BOGEY", round(total * 1.35, 0), total)) %>% 
  ungroup() %>% 
  rowwise() %>% 
  mutate(samples = list(rep(score_type, modified_total))) %>% 
  select(.cluster, samples) %>% 
  nest(data = c(samples))

cluster_samples <- 
  hole_samples_nested_tbl %>%
  select(data) %>% 
  pmap( ~ pull(.x))

cluster_samples %>% 
  purrr::pluck(1) %>% 
  unlist()
```



# Simulation Framework
```{r}
holes_clustered_nested <- 
  holes_clustered_tbl %>% 
  select(player_name, score_type, .cluster) %>% 
  nest(scores = -player_name)

dr <- read_csv("dr.csv") %>% 
  janitor::clean_names() %>% 
  filter(!player %in% c("Daniel Berger")) %>% 
  mutate(player = case_when(
    player == "Alex Noren" ~ "Alexander Noren",
    player == "Robert Macintyre" ~ "Robert MacIntyre",
    player == "Erik Van Rooyen" ~ "Erik van Rooyen",
    player == "Rafa Cabrera Bello" ~ "Rafael Cabrera Bello",
    player == "Seung-Yul Noh" ~ "Seung-yul Noh",
    TRUE ~ player
  )) %>% 
  pull(player)

df <- 
  holes_clustered_nested %>% 
  filter(player_name == "Austin Eckroat") %>% 
  unnest(scores) %>% 
  View()



get_player_sims <- function(sims, scores, n_samples) {
  
  # generates player simulations
  
  if (n_samples == 1) {
    tibble(score_type = sample(scores, sims, replace = TRUE)) %>%
      mutate(sim = str_glue("X{row_number()}") %>% as.character(),
             .before = score_type)
  } else if (n_samples > 1) {
    data.frame(replicate(sims,
                         sample(scores, n_samples, replace = TRUE))) %>%
      pivot_longer(cols = everything(),
                   names_to = "sim",
                   values_to = "score_type")
  }  else {
    tibble(sim = character(),
           score_type = character())
  }
  
}



player_sim_func <- function(df, 
                            n = 5, 
                            p3_easy = 0, 
                            p3_hard = 4,
                            p4_easy = 3,
                            p4_hard = 9,
                            p5      = 2){
  
  # add check easy + medium + hard = 18
  
  # add weighting for recent vs. long form?
  
  scores_easy_p3 <- 
    df %>% 
    filter(.cluster == 3) %>% 
    pull(score_type)
  
  scores_hard_p3 <- 
    df %>% 
    filter(.cluster == 5) %>% 
    pull(score_type)
    
  scores_easy_p4 <- 
    df %>% 
    filter(.cluster == 1) %>% 
    pull(score_type)
  
  scores_hard_p4 <- 
    df %>% 
    filter(.cluster == 3) %>% 
    pull(score_type)
  
  scores_p5 <- 
    df %>% 
    filter(.cluster == 4) %>% 
    pull(score_type)
    
  # Round 1 Simulations
  rd_1_p3_sims_easy <- get_player_sims(sims = n, scores_easy_p3, p3_easy)
  rd_1_p3_sims_hard <- get_player_sims(sims = n, scores_hard_p3, p3_hard)
  rd_1_p4_sims_easy <- get_player_sims(sims = n, scores_easy_p4, p4_easy)
  rd_1_p4_sims_hard <- get_player_sims(sims = n, scores_hard_p4, p4_hard)
  rd_1_p5_sims      <- get_player_sims(sims = n, scores_p5, p5)
  
  # Round 2 Simulations
  rd_2_p3_sims_easy <- get_player_sims(sims = n, scores_easy_p3, p3_easy)
  rd_2_p3_sims_hard <- get_player_sims(sims = n, scores_hard_p3, p3_hard)
  rd_2_p4_sims_easy <- get_player_sims(sims = n, scores_easy_p4, p4_easy)
  rd_2_p4_sims_hard <- get_player_sims(sims = n, scores_hard_p4, p4_hard)
  rd_2_p5_sims      <- get_player_sims(sims = n, scores_p5, p5)
  
  # Round 3 Simulations
  rd_3_p3_sims_easy <- get_player_sims(sims = n, scores_easy_p3, p3_easy)
  rd_3_p3_sims_hard <- get_player_sims(sims = n, scores_hard_p3, p3_hard)
  rd_3_p4_sims_easy <- get_player_sims(sims = n, scores_easy_p4, p4_easy)
  rd_3_p4_sims_hard <- get_player_sims(sims = n, scores_hard_p4, p4_hard)
  rd_3_p5_sims      <- get_player_sims(sims = n, scores_p5, p5)
  
  # Round 4 Simulations
  rd_4_p3_sims_easy <- get_player_sims(sims = n, scores_easy_p3, p3_easy)
  rd_4_p3_sims_hard <- get_player_sims(sims = n, scores_hard_p3, p3_hard)
  rd_4_p4_sims_easy <- get_player_sims(sims = n, scores_easy_p4, p4_easy)
  rd_4_p4_sims_hard <- get_player_sims(sims = n, scores_hard_p4, p4_hard)
  rd_4_p5_sims      <- get_player_sims(sims = n, scores_p5, p5)
  
  
  # Calculate Draft Kings Points and Score for Simulation
  rds_1_and_2_tbl <- 
    bind_rows(rd_1_p3_sims_easy, rd_1_p3_sims_hard, rd_1_p4_sims_easy, rd_1_p4_sims_hard, rd_1_p5_sims,
              rd_2_p3_sims_easy, rd_2_p3_sims_hard, rd_2_p4_sims_easy, rd_2_p4_sims_hard, rd_2_p5_sims) %>%
    mutate(
      dk_pts_rds_1_and_2 = case_when(
        score_type %in% c("DOUBLE_EAGLE") ~ 13,
        score_type %in% c("EAGLE") ~ 8,
        score_type %in% c("BIRDIE") ~ 3,
        score_type %in% c("PAR") ~ .5,
        score_type %in% c("BOGEY") ~ -.5,
        score_type %in% c("DOUBLE_BOGEY", "TRIPLE_BOGEY", "OTHER") ~ -1
      ),
      score_rds_1_and_2 = case_when(
        score_type %in% c("DOUBLE_EAGLE") ~ -3,
        score_type %in% c("EAGLE") ~ -2,
        score_type %in% c("BIRDIE") ~ -1,
        score_type %in% c("PAR") ~ 0,
        score_type %in% c("BOGEY") ~ 1,
        score_type %in% c("DOUBLE_BOGEY") ~ 2,
        score_type %in% c("TRIPLE_BOGEY") ~ 3,
        score_type %in% c("OTHER") ~ 4
      )
    ) %>%
    group_by(sim) %>% 
    summarise(across(dk_pts_rds_1_and_2:score_rds_1_and_2, .fns = sum))
  
  rds_3_and_4_tbl <- 
    bind_rows(rd_3_p3_sims_easy, rd_3_p3_sims_hard, rd_3_p4_sims_easy, rd_3_p4_sims_hard, rd_3_p5_sims,
              rd_4_p3_sims_easy, rd_4_p3_sims_hard, rd_4_p4_sims_easy, rd_4_p4_sims_hard, rd_4_p5_sims) %>%
    mutate(
      dk_pts_rds_3_and_4 = case_when(
        score_type %in% c("DOUBLE_EAGLE") ~ 13,
        score_type %in% c("EAGLE") ~ 8,
        score_type %in% c("BIRDIE") ~ 3,
        score_type %in% c("PAR") ~ .5,
        score_type %in% c("BOGEY") ~ -.5,
        score_type %in% c("DOUBLE_BOGEY", "TRIPLE_BOGEY", "OTHER") ~ -1
      ),
      score_rds_3_and_4 = case_when(
        score_type %in% c("DOUBLE_EAGLE") ~ -3,
        score_type %in% c("EAGLE") ~ -2,
        score_type %in% c("BIRDIE") ~ -1,
        score_type %in% c("PAR") ~ 0,
        score_type %in% c("BOGEY") ~ 1,
        score_type %in% c("DOUBLE_BOGEY") ~ 2,
        score_type %in% c("TRIPLE_BOGEY") ~ 3,
        score_type %in% c("OTHER") ~ 4
      )
    ) %>%
    group_by(sim) %>% 
    summarise(across(dk_pts_rds_3_and_4:score_rds_3_and_4, .fns = sum))
  
  left_join(rds_1_and_2_tbl, rds_3_and_4_tbl)
  
}


```

```{r}
# First Two Rounds Sim
# made_cut_tbl <- 
honda_sims <- 
  holes_clustered_nested %>% 
  filter(player_name %in% dr) %>% 
  pull(scores) %>% 
  future_map(~ player_sim_func(.x, n = 10000)) %>% 
  enframe() %>% 
  bind_cols(select(holes_clustered_nested, player_name) %>% filter(player_name %in% dr)) %>%
  unnest(value) %>% 
  group_by(sim) %>% 
  mutate(rd_1_and_2_rank = min_rank(score_rds_1_and_2)) %>% 
  ungroup() %>% 
  mutate(dk_pts_rds_3_and_4 = if_else(rd_1_and_2_rank > 65, 0, dk_pts_rds_3_and_4),
         score_rds_3_and_4 = if_else(rd_1_and_2_rank > 65, 100, score_rds_3_and_4)) %>% 
  mutate(dk_scoring_pts = dk_pts_rds_1_and_2 + dk_pts_rds_3_and_4,
         total_score = score_rds_1_and_2 + score_rds_3_and_4) %>% 
  group_by(sim) %>% 
  mutate(final_pos = min_rank(total_score)) %>%
  mutate(dk_finish_pts = case_when(
    final_pos == 1 ~ 30,
    final_pos == 2 ~ 20,
    final_pos == 3 ~ 18,
    final_pos == 4 ~ 16,
    final_pos == 5 ~ 14,
    final_pos == 6 ~ 12,
    final_pos == 7 ~ 10,
    final_pos == 8 ~ 9,
    final_pos == 9 ~ 8,
    final_pos == 10 ~ 7,
    final_pos %in% c(11:15) ~ 6,
    final_pos %in% c(16:20) ~ 5,
    final_pos %in% c(21:25) ~ 4,
    final_pos %in% c(26:30) ~ 3,
    final_pos %in% c(31:40) ~ 2,
    final_pos %in% c(41:50) ~ 1,
    TRUE ~ 0
  )) %>% 
  mutate(dk_total_pts = dk_scoring_pts + dk_finish_pts) %>% 
  mutate(dk_pts_rank = min_rank(-dk_total_pts)) %>% 
  ungroup()


  

my_sims <- 
  honda_sims %>% 
  group_by(player_name) %>% 
  summarise(win_perc = sum(final_pos == 1)/10000*100,
            top5_perc = sum(final_pos <= 5)/10000*100,
            top20_perc = sum(final_pos <= 20)/10000*100,
            avg_dk_points = mean(dk_total_pts),
            top5_dk = sum(dk_pts_rank <= 5)/10000*100,
            top20_dk = sum(dk_pts_rank <= 20)/10000*100) %>% 
  arrange(desc(top20_dk)) %>% 
  ungroup()

roto <- read_csv("dr.csv") %>% 
  janitor::clean_names() %>% 
  mutate(player = case_when(
    player == "Alex Noren" ~ "Alexander Noren",
    player == "Robert Macintyre" ~ "Robert MacIntyre",
    player == "Erik Van Rooyen" ~ "Erik van Rooyen",
    player == "Rafa Cabrera Bello" ~ "Rafael Cabrera Bello",
    player == "Seung-Yul Noh" ~ "Seung-yul Noh",
    TRUE ~ player
  )) %>% 
  left_join(my_sims, by = c("player" = "player_name"))

dr_pred_data <- 
  my_sims %>% 
  left_join(select(roto, player, ownership, salary, points), by = c("player_name" = "player"))
```


```{r}

g1 <- 
  dr_pred_data %>% 
  # filter(player %in% c("Tony Finau", "Sungjae Im", "Matthew Wolff", "Brooks Koepka")) %>% 
  filter(salary %in% c(6000:9000)) %>%
  filter(points > 0) %>% 
  mutate(label = str_glue("Player: {player_name}
                          Salary: {salary}")) %>% 
  ggplot(aes(points, top5_dk)) +
  geom_point(aes(size = ownership, text = label))



ggplotly(g1)
```

```{r}

honda_sims %>% 
  filter(final_pos == 1) %>% 
  ggplot(aes(total_score)) + 
  geom_histogram()
```








